.\" SPDX-License-Identifier: GPL-2.0-or-later
.\" -*- nroff -*-
.\"
.\" Copyright (C) 2018 Linutronix GmbH
.\" Author: Benedikt Spranger <b.spranger@linutronix.de>
.\"
.TH TESTPIN 1 "July 14, 2018"
.\" Please update the above date whenever this man page is modified.
.\"
.SH NAME
testpin \- libgpio example application
.SH SYNOPSIS
.B testpin
.SH DESCRIPTION
testpin accqurires a previously configured GPIO pin "test" and releases
it directly afterwards.
.SH AUTHOR
Manuel Traut manut@linutronix.de
